### ISSUE TITLE
C:/C: Bug and Suggestions

### ISSUE THREAD

**Issue by kcbence** [Enderbyte-Programs/CraftServerSetup#4] opened 2023-10-04 12:11 UTC
When you go to select java installation
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/03b32edc-e172-4453-96f5-568e49c09bf4)
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/3d200c6d-5e12-4550-a3e3-52afc40c70dd)
It lands you on %userprofile% 
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/c3c8e71b-114b-4406-a189-eae106f97d19)
I press "B" once to go up No problem so far
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/86581402-fd25-4079-a9be-df4acf3bf699)
If i press again it puts u to "C:" instead of "C:\" and "C:" is not a valid directory
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/5d9cfc9e-9603-470a-b6f9-39101406bbe3)
If i press again it finally goes to "C:\"
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/33e01136-3f91-4dc1-b73b-e8f38887da16)
And if i go to any folder and press "B" again it does the same 

2. And also when something happens I cant view the log (no permission issues or anything else to my knowledge)
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/d80e21f7-b89f-407e-98a1-f9fee83e8a5e)

3. Recommendations
You could pop out the mc server console to a seperate window and maybe an other window where the current users are there and there would be options to e.g kick, ban, whois info, or if essentials is there some essentials command e.g /whois /spawnmob etc and another window (or if the windows are too much put it everything into 1 window and use option menu) where you can change the time , weather, gamerules, etc
4. And couldnt export the server when i choose the folder it said:
![image](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/127664036/07ff2832-4108-423a-b437-516ccd00a4bd)

And maybe some popular plugins (coreprotect,essentials,multiverse) could have a seperate menu where you can use the plugin in a terminal like ui

**Comment by Enderbyte09** [comment] 2023-10-04 14:50
Thank you for your bug report.
This has been labelled high severity and will be fixed as soon as possible. It also appears that you have run into the large problem that the colours system breaks down frequently on Windows.

**Comment by Enderbyte09** [comment] 2023-10-04 15:58
Bug no. 1 is a problem in cursesplus. It is being fixed right now.

**Comment by Enderbyte09** [comment] 2023-10-04 17:25
Bug no. 2 is caused by a bug where I change the directory to the logs dir without first checking if such a directory exists

**Comment by Enderbyte09** [comment] 2023-10-04 17:27
I was unable to replicate bug no. 3. Could you please elaborate more on what directory you chose?

**Comment by kcbence** [comment] 2023-10-04 17:53
I can't replicate it either it was run on a computer that is not in my hands right now so we can close that issue until I encounter it again

**Closed** 2023-10-04 18:06 UTC
Labels: bug, High Severity
